env:
  node: true

extends:
  - airbnb-base
  - airbnb-typescript/base

parserOptions:
  project:
    - ./tsconfig.json
    - ./test/tsconfig.json

rules:
  quotes:
    - error
    - single
  import/extensions: off

overrides:
  - files:
      - "*.spec.ts"
      - "*.test.ts"
    rules:
      '@typescript-eslint/no-shadow': off
